expose_php=Off
memory_limit=512M
max_execution_time=120
max_input_vars=5000
post_max_size=32M
upload_max_filesize=32M
date.timezone=America/Bahia
session.cookie_httponly=1
session.cookie_samesite=Lax
