@extends('layouts.app')
@section('title','Usuários')
@section('content')
<x-page-header title="Usuários da empresa" description="Acessos administrativos vinculados à empresa atual com papéis e permissões."><x-slot:actions><button class="btn btn-primary" data-modal-open="user-create">＋ Novo usuário</button></x-slot:actions></x-page-header>
<div class="toolbar"><form class="filter-form"><input class="search-input" name="q" value="{{ request('q') }}" placeholder="Nome do usuário"><button class="btn btn-secondary">Buscar</button></form><span class="cell-subtitle">{{ $users->total() }} usuário(s)</span></div>
<div class="card"><div class="table-wrap desktop-table"><table><thead><tr><th>Usuário</th><th>Login</th><th>E-mail</th><th>Perfil</th><th>Segurança</th><th>Status</th><th></th></tr></thead><tbody>@forelse($users as $user)<tr><td class="cell-title">{{ $user->name }}</td><td>{{ $user->login ?: '—' }}</td><td>{{ $user->email }}</td><td>{{ $roles->firstWhere('id',$user->pivot->role_id)?->name ?: 'Sem perfil' }}</td><td>{{ $user->two_factor_confirmed_at ? '2FA ativo' : '2FA pendente' }}<div class="cell-subtitle">{{ $user->must_change_password ? 'Troca de senha obrigatória' : 'Senha definida' }}</div></td><td><x-status-badge :value="$user->active?'active':'inactive'" /></td><td><div class="table-actions"><button class="btn btn-secondary btn-sm" data-modal-open="user-edit-{{ $user->id }}">Editar</button>@unless($user->is(auth()->user()) || $user->is_super_admin)<form method="post" action="{{ route('users.destroy',$user) }}">@csrf @method('delete')<button class="btn btn-ghost btn-sm" data-confirm="Remover o vínculo deste usuário?">Remover</button></form>@endunless</div></td></tr>@empty<tr><td colspan="7"><x-empty-state title="Nenhum usuário" text="Cadastre operadores, técnicos, financeiros ou usuários de consulta." /></td></tr>@endforelse</tbody></table></div><div class="card-list">@foreach($users as $user)<div class="mobile-card"><div class="cell-title">{{ $user->name }}</div><div class="cell-subtitle">{{ $user->email }}</div><div class="mobile-card-grid"><div><div class="mobile-card-label">Perfil</div><div>{{ $roles->firstWhere('id',$user->pivot->role_id)?->name ?: '—' }}</div></div><div><div class="mobile-card-label">Status</div><x-status-badge :value="$user->active?'active':'inactive'" /></div></div><div class="table-actions" style="margin-top:12px"><button class="btn btn-secondary btn-sm" data-modal-open="user-edit-{{ $user->id }}">Editar</button></div></div>@endforeach</div>@include('partials.pagination',['paginator'=>$users])</div>
<x-modal id="user-create" title="Novo usuário" size="lg"><form method="post" action="{{ route('users.store') }}">@csrf @include('users._form',['user'=>null])</form></x-modal>
@foreach($users as $user)<x-modal id="user-edit-{{ $user->id }}" title="Editar usuário" size="lg"><form method="post" action="{{ route('users.update',$user) }}">@csrf @method('put') @include('users._form',['user'=>$user])</form></x-modal>@endforeach
@endsection
