@php($s=$subscriber??null)
<div class="form-grid">
<div class="col-3"><label>Tipo</label><select name="type" required><option value="person" @selected(old('type',$s?->type)==='person')>Pessoa física</option><option value="company" @selected(old('type',$s?->type)==='company')>Pessoa jurídica</option></select></div>
<div class="col-6"><label>Nome / Razão social</label><input name="name" value="{{ old('name',$s?->name) }}" required></div><div class="col-3"><label>CPF/CNPJ</label><input name="document" value="{{ old('document',$s?->document) }}"></div>
<div class="col-4"><label>E-mail</label><input type="email" name="email" value="{{ old('email',$s?->email) }}"></div><div class="col-4"><label>Telefone</label><input name="phone" value="{{ old('phone',$s?->phone) }}"></div><div class="col-4"><label>WhatsApp</label><input name="whatsapp" value="{{ old('whatsapp',$s?->whatsapp) }}"></div>
<div class="col-3"><label>CEP</label><input name="zip_code" value="{{ old('zip_code',$s?->zip_code) }}"></div><div class="col-6"><label>Logradouro</label><input name="street" value="{{ old('street',$s?->street) }}"></div><div class="col-3"><label>Número</label><input name="number" value="{{ old('number',$s?->number) }}"></div>
<div class="col-4"><label>Complemento</label><input name="complement" value="{{ old('complement',$s?->complement) }}"></div><div class="col-4"><label>Bairro</label><input name="district" value="{{ old('district',$s?->district) }}"></div><div class="col-3"><label>Cidade</label><input name="city" value="{{ old('city',$s?->city) }}"></div><div class="col-1"><label>UF</label><input name="state" maxlength="2" value="{{ old('state',$s?->state) }}"></div>
<div class="col-3"><label>Situação</label><select name="status"><option value="active" @selected(old('status',$s?->status??'active')==='active')>Ativo</option><option value="inactive" @selected(old('status',$s?->status)==='inactive')>Inativo</option><option value="blocked" @selected(old('status',$s?->status)==='blocked')>Bloqueado</option></select></div><div class="col-9"><label>Observações</label><textarea name="notes">{{ old('notes',$s?->notes) }}</textarea></div>
</div>
<div class="modal-footer"><button type="button" class="btn btn-secondary" data-modal-close>Cancelar</button><button class="btn btn-primary" type="submit">Salvar cliente</button></div>
