@extends('layouts.app')
@section('title','Clientes')
@section('content')
<x-page-header title="Clientes" description="Cadastro central de assinantes, responsáveis e dados de contato."><x-slot:actions><button class="btn btn-primary" data-modal-open="subscriber-create">＋ Novo cliente</button></x-slot:actions></x-page-header>
<div class="toolbar"><form class="filter-form"><input class="search-input" name="q" value="{{ request('q') }}" placeholder="Buscar nome ou documento"><button class="btn btn-secondary">Buscar</button>@if(request('q'))<a class="btn btn-ghost" href="{{ route('subscribers.index') }}">Limpar</a>@endif</form><span class="cell-subtitle">{{ $subscribers->total() }} registro(s)</span></div>
<div class="card"><div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Documento</th><th>Contato</th><th>Cidade</th><th>Status</th><th></th></tr></thead><tbody>@forelse($subscribers as $subscriber)<tr><td><div class="cell-title">{{ $subscriber->name }}</div><div class="cell-subtitle">{{ $subscriber->type==='company'?'Pessoa jurídica':'Pessoa física' }}</div></td><td>{{ $subscriber->document ?: '—' }}</td><td><div>{{ $subscriber->phone ?: $subscriber->whatsapp ?: '—' }}</div><div class="cell-subtitle">{{ $subscriber->email }}</div></td><td>{{ $subscriber->city ? $subscriber->city.'/'.$subscriber->state : '—' }}</td><td><x-status-badge :value="$subscriber->status" /></td><td><div class="table-actions"><button class="btn btn-secondary btn-sm" data-modal-open="subscriber-edit-{{ $subscriber->id }}">Editar</button><form method="post" action="{{ route('subscribers.destroy',$subscriber) }}">@csrf @method('delete')<button class="btn btn-ghost btn-sm" data-confirm="Excluir este cliente?">Excluir</button></form></div></td></tr>@empty<tr><td colspan="6"><x-empty-state /></td></tr>@endforelse</tbody></table></div>@include('partials.pagination',['paginator'=>$subscribers])</div>
<x-modal id="subscriber-create" title="Novo cliente" size="lg"><form method="post" action="{{ route('subscribers.store') }}">@csrf @include('subscribers._form',['subscriber'=>null])</form></x-modal>
@foreach($subscribers as $subscriber)<x-modal id="subscriber-edit-{{ $subscriber->id }}" title="Editar cliente" size="lg"><form method="post" action="{{ route('subscribers.update',$subscriber) }}">@csrf @method('put') @include('subscribers._form',['subscriber'=>$subscriber])</form></x-modal>@endforeach
@endsection
