@php($c=$company??null)
<div class="section-card"><h3 class="section-title">Dados cadastrais</h3><div class="form-grid">
<div class="col-7"><label>Razão social</label><input name="legal_name" value="{{ old('legal_name',$c?->legal_name) }}" required></div><div class="col-5"><label>Nome fantasia</label><input name="trade_name" value="{{ old('trade_name',$c?->trade_name) }}"></div>
<div class="col-3"><label>CPF/CNPJ</label><input name="document" value="{{ old('document',$c?->document) }}"></div><div class="col-5"><label>E-mail</label><input type="email" name="email" value="{{ old('email',$c?->email) }}"></div><div class="col-4"><label>Telefone</label><input name="phone" value="{{ old('phone',$c?->phone) }}"></div>
<div class="col-4"><label>Plano contratado</label><input name="subscription_plan" value="{{ old('subscription_plan',$c?->subscription_plan) }}"></div><div class="col-8"><label>Limites em JSON</label><textarea name="usage_limits_json" rows="3" placeholder='{"users":25,"mikrotiks":5,"vouchers":5000,"subscribers":1000,"plans":20,"accesses":1000}'>{{ old('usage_limits_json',$c?->usage_limits ? json_encode($c->usage_limits, JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) : '') }}</textarea></div><div class="col-4"><label>Status</label><select name="status">@foreach(['active'=>'Ativa','suspended'=>'Suspensa','cancelled'=>'Cancelada'] as $v=>$l)<option value="{{ $v }}" @selected(old('status',$c?->status??'active')===$v)>{{ $l }}</option>@endforeach</select></div><div class="col-4"><label class="checkbox"><input type="checkbox" name="active" value="1" @checked(old('active',$c?->active??true))> Cadastro ativo</label></div>
</div></div>
<div class="section-card"><h3 class="section-title">Endereço</h3><div class="form-grid"><div class="col-2"><label>CEP</label><input name="zip_code" value="{{ old('zip_code',$c?->zip_code) }}"></div><div class="col-5"><label>Logradouro</label><input name="street" value="{{ old('street',$c?->street) }}"></div><div class="col-2"><label>Número</label><input name="number" value="{{ old('number',$c?->number) }}"></div><div class="col-3"><label>Complemento</label><input name="complement" value="{{ old('complement',$c?->complement) }}"></div><div class="col-4"><label>Bairro</label><input name="district" value="{{ old('district',$c?->district) }}"></div><div class="col-6"><label>Cidade</label><input name="city" value="{{ old('city',$c?->city) }}"></div><div class="col-2"><label>UF</label><input name="state" maxlength="2" value="{{ old('state',$c?->state) }}"></div></div></div>
@if(!$c)<div class="section-card"><h3 class="section-title">Administrador inicial</h3><label class="checkbox"><input type="checkbox" name="create_admin" value="1" checked> Criar automaticamente o usuário administrador</label><div class="form-grid"><div class="col-6"><label>Nome</label><input name="admin_name" value="{{ old('admin_name') }}"></div><div class="col-6"><label>E-mail</label><input type="email" name="admin_email" value="{{ old('admin_email') }}"></div><div class="col-4"><label>Login</label><input name="admin_login" value="{{ old('admin_login') }}"></div><div class="col-4"><label>Senha inicial</label><input type="password" name="admin_password"></div><div class="col-4"><label>Confirmar senha</label><input type="password" name="admin_password_confirmation"></div><div class="col-6"><label>Perfil</label><select name="admin_role_id"><option value="">Selecione</option>@foreach($roles as $role)<option value="{{ $role->id }}">{{ $role->name }}</option>@endforeach</select></div><div class="col-6"><label class="checkbox"><input type="checkbox" name="send_password_link" value="1" checked> Enviar instruções para definição de senha</label></div></div></div>@endif
<div class="modal-footer"><button type="button" class="btn btn-secondary" data-modal-close>Cancelar</button><button class="btn btn-primary">Salvar empresa</button></div>
