@extends('layouts.app')
@section('title','Empresas')
@section('content')
<x-page-header title="Empresas do tenant" description="Cadastros vinculados ao tenant atual, com criação opcional do administrador responsável."><x-slot:actions><button class="btn btn-primary" data-modal-open="company-create">＋ Nova empresa</button></x-slot:actions></x-page-header>
<div class="toolbar"><form class="filter-form"><input class="search-input" name="q" value="{{ request('q') }}" placeholder="Razão social"><select name="status"><option value="">Todos os status</option>@foreach(['active'=>'Ativa','suspended'=>'Suspensa','cancelled'=>'Cancelada'] as $v=>$l)<option value="{{ $v }}" @selected(request('status')===$v)>{{ $l }}</option>@endforeach</select><button class="btn btn-secondary">Filtrar</button></form><span class="cell-subtitle">{{ $companies->total() }} empresa(s)</span></div>
<div class="card"><div class="table-wrap desktop-table"><table><thead><tr><th>Empresa</th><th>Documento</th><th>Contato</th><th>Plano</th><th>Status</th><th></th></tr></thead><tbody>@forelse($companies as $company)<tr><td><div class="cell-title">{{ $company->trade_name ?: $company->legal_name }}</div><div class="cell-subtitle">{{ $company->legal_name }}</div></td><td>{{ $company->document ?: '—' }}</td><td>{{ $company->email ?: '—' }}<div class="cell-subtitle">{{ $company->phone }}</div></td><td>{{ $company->subscription_plan ?: 'Não definido' }}</td><td><x-status-badge :value="$company->status" /></td><td><div class="table-actions"><button class="btn btn-secondary btn-sm" data-modal-open="company-edit-{{ $company->id }}">Editar</button><form method="post" action="{{ route('companies.destroy',$company) }}">@csrf @method('delete')<button class="btn btn-ghost btn-sm" data-confirm="Excluir esta empresa?">Excluir</button></form></div></td></tr>@empty<tr><td colspan="6"><x-empty-state title="Nenhuma empresa" text="Crie a primeira empresa para organizar usuários, equipamentos e acessos." /></td></tr>@endforelse</tbody></table></div><div class="card-list">@foreach($companies as $company)<div class="mobile-card"><div class="cell-title">{{ $company->trade_name ?: $company->legal_name }}</div><div class="mobile-card-grid"><div><div class="mobile-card-label">Documento</div><div class="mobile-card-value">{{ $company->document ?: '—' }}</div></div><div><div class="mobile-card-label">Status</div><x-status-badge :value="$company->status" /></div></div><div class="table-actions" style="margin-top:12px"><button class="btn btn-secondary btn-sm" data-modal-open="company-edit-{{ $company->id }}">Editar</button></div></div>@endforeach</div>@include('partials.pagination',['paginator'=>$companies])</div>
<x-modal id="company-create" title="Nova empresa" size="lg"><form method="post" action="{{ route('companies.store') }}">@csrf @include('companies._form',['company'=>null])</form></x-modal>
@foreach($companies as $company)<x-modal id="company-edit-{{ $company->id }}" title="Editar empresa" size="lg"><form method="post" action="{{ route('companies.update',$company) }}">@csrf @method('put') @include('companies._form',['company'=>$company])</form></x-modal>@endforeach
@endsection
