@extends('layouts.app')
@section('title','Vouchers')
@section('content')
<x-page-header title="Vouchers dinâmicos" description="Geração individual ou em lote, validade fixa ou iniciada no primeiro acesso, impressão e sincronização."><x-slot:actions>@can('create', App\Models\Voucher::class)<button class="btn btn-primary" data-modal-open="voucher-create">＋ Gerar vouchers</button>@endcan</x-slot:actions></x-page-header>
<div class="metric-grid"><x-metric-card label="Disponíveis" :value="$vouchers->getCollection()->where('status','available')->count()" note="Na página atual"/><x-metric-card label="Ativos" :value="$vouchers->getCollection()->where('status','active')->count()" note="Em utilização"/><x-metric-card label="Expirados" :value="$vouchers->getCollection()->where('status','expired')->count()" note="Na página atual"/><x-metric-card label="Total encontrado" :value="$vouchers->total()" note="Após os filtros"/></div>
<div class="toolbar"><form class="filter-form"><input class="search-input" name="q" value="{{ request('q') }}" placeholder="Código do voucher"><select name="status"><option value="">Todos os status</option>@foreach(['available'=>'Disponível','active'=>'Ativo','used'=>'Utilizado','expired'=>'Expirado','blocked'=>'Bloqueado','cancelled'=>'Cancelado'] as $v=>$l)<option value="{{ $v }}" @selected(request('status')===$v)>{{ $l }}</option>@endforeach</select><select name="batch_id"><option value="">Todos os lotes</option>@foreach($batches as $batch)<option value="{{ $batch->id }}" @selected(request('batch_id')===$batch->id)>{{ $batch->name }}</option>@endforeach</select><button class="btn btn-secondary">Filtrar</button></form></div>
<div class="card"><div class="table-wrap desktop-table"><table><thead><tr><th>Código</th><th>Lote</th><th>Plano/perfil</th><th>MikroTik</th><th>Validade</th><th>Acessos</th><th>Status</th><th></th></tr></thead><tbody>@forelse($vouchers as $voucher)<tr><td><div class="cell-title kbd">{{ $voucher->code }}</div><div class="cell-subtitle">{{ $voucher->device_identifier ?: 'Sem dispositivo' }}</div></td><td>{{ $voucher->batch?->name ?: 'Avulso' }}</td><td>{{ $voucher->profile?->name ?: $voucher->plan?->name ?: 'Padrão' }}<div class="cell-subtitle">{{ $voucher->speed_limit ?: 'Sem limite específico' }}</div></td><td>{{ $voucher->mikrotik?->name ?: 'RADIUS' }}</td><td>{{ optional($voucher->expires_at)->format('d/m/Y H:i') ?: ($voucher->validity_duration_minutes ? $voucher->validity_duration_minutes.' min após primeiro acesso' : 'Sem expiração') }}</td><td>{{ optional($voucher->first_access_at)->format('d/m/Y H:i') ?: 'Nunca' }}<div class="cell-subtitle">Último: {{ optional($voucher->last_access_at)->format('d/m/Y H:i') ?: '—' }}</div></td><td><x-status-badge :value="$voucher->status" /></td><td>@can('update',$voucher)<div class="table-actions">@if($voucher->mikrotik)<form method="post" action="{{ route('vouchers.sync',$voucher) }}">@csrf<button class="btn btn-secondary btn-sm">Sincronizar</button></form>@endif @if(in_array($voucher->status,['available','active']))<form method="post" action="{{ route('vouchers.block',$voucher) }}">@csrf<button class="btn btn-warning btn-sm">Bloquear</button></form>@else<form method="post" action="{{ route('vouchers.reactivate',$voucher) }}">@csrf<button class="btn btn-success btn-sm">Reativar</button></form>@endif<form method="post" action="{{ route('vouchers.cancel',$voucher) }}">@csrf<button class="btn btn-ghost btn-sm" data-confirm="Cancelar voucher?">Cancelar</button></form></div>@endcan</td></tr>@empty<tr><td colspan="8"><x-empty-state title="Nenhum voucher" text="Gere um lote para disponibilizar acessos temporários." /></td></tr>@endforelse</tbody></table></div><div class="card-list">@foreach($vouchers as $voucher)<div class="mobile-card"><div class="cell-title kbd">{{ $voucher->code }}</div><div class="mobile-card-grid"><div><div class="mobile-card-label">Plano</div><div>{{ $voucher->profile?->name ?: $voucher->plan?->name ?: 'Padrão' }}</div></div><div><div class="mobile-card-label">Status</div><x-status-badge :value="$voucher->status" /></div><div><div class="mobile-card-label">Expiração</div><div>{{ optional($voucher->expires_at)->format('d/m/Y H:i') ?: 'Primeiro acesso' }}</div></div></div></div>@endforeach</div>@include('partials.pagination',['paginator'=>$vouchers])</div>
@can('export', App\Models\Voucher::class)@if($batches->isNotEmpty())<div class="card" style="margin-top:16px"><div class="card-header"><div><div class="card-title">Lotes recentes</div><div class="card-subtitle">Impressão e exportação das credenciais</div></div></div><div class="card-body"><div class="toolbar-actions">@foreach($batches->take(10) as $batch)<a class="btn btn-secondary btn-sm" href="{{ route('vouchers.print',$batch) }}" target="_blank">{{ $batch->name }} · imprimir</a><a class="btn btn-ghost btn-sm" href="{{ route('vouchers.csv',$batch) }}">CSV</a><a class="btn btn-ghost btn-sm" href="{{ route('vouchers.pdf',$batch) }}">PDF</a>@endforeach</div></div></div>@endif @endcan
@can('create', App\Models\Voucher::class)<x-modal id="voucher-create" title="Gerar vouchers" size="lg"><form method="post" action="{{ route('vouchers.store') }}">@csrf @include('vouchers._form')</form></x-modal>@endcan
@endsection
