@extends('layouts.app')
@section('title','Acessos')
@section('content')
<x-page-header title="Usuários pré-cadastrados" description="Credenciais Hotspot e PPPoE, plano, perfil, validade, limite de conexão e sincronização SSH."><x-slot:actions><button class="btn btn-primary" data-modal-open="access-create">＋ Novo acesso</button></x-slot:actions></x-page-header>
<div class="toolbar"><form class="filter-form"><input class="search-input" name="q" value="{{ request('q') }}" placeholder="Login do cliente"><button class="btn btn-secondary">Buscar</button></form><span class="cell-subtitle">{{ $accesses->total() }} acesso(s)</span></div>
<div class="card"><div class="table-wrap desktop-table"><table><thead><tr><th>Login</th><th>Cliente</th><th>Serviço</th><th>Plano/perfil</th><th>Equipamento</th><th>Validade</th><th>Status</th><th></th></tr></thead><tbody>@forelse($accesses as $access)<tr><td><div class="cell-title">{{ $access->username }}</div><div class="cell-subtitle">{{ $access->caller_id ?: 'Sem vínculo de dispositivo' }}</div></td><td>{{ $access->subscriber->name }}</td><td>{{ strtoupper($access->service_type->value) }}</td><td>{{ $access->profile?->name ?: $access->plan->name }}<div class="cell-subtitle">{{ $access->profile?->rate_limit ?: $access->plan->rate_limit }}</div></td><td>{{ $access->mikrotik?->name ?: 'RADIUS / qualquer NAS' }}</td><td>{{ optional($access->starts_at)->format('d/m/Y') ?: 'Imediato' }} → {{ optional($access->expires_at)->format('d/m/Y') ?: 'Sem expiração' }}</td><td><x-status-badge :value="$access->status" /></td><td><div class="table-actions">@if($access->mikrotik)<form method="post" action="{{ route('accesses.sync',$access) }}">@csrf<button class="btn btn-success btn-sm">Sincronizar</button></form>@endif<button class="btn btn-secondary btn-sm" data-modal-open="access-edit-{{ $access->id }}">Editar</button><form method="post" action="{{ route('accesses.destroy',$access) }}">@csrf @method('delete')<button class="btn btn-ghost btn-sm" data-confirm="Excluir esta credencial?">Excluir</button></form></div></td></tr>@empty<tr><td colspan="8"><x-empty-state /></td></tr>@endforelse</tbody></table></div><div class="card-list">@foreach($accesses as $access)<div class="mobile-card"><div class="cell-title">{{ $access->username }}</div><div class="cell-subtitle">{{ $access->subscriber->name }}</div><div class="mobile-card-grid"><div><div class="mobile-card-label">Plano</div><div>{{ $access->profile?->name ?: $access->plan->name }}</div></div><div><div class="mobile-card-label">Status</div><x-status-badge :value="$access->status" /></div></div><div class="table-actions" style="margin-top:12px">@if($access->mikrotik)<form method="post" action="{{ route('accesses.sync',$access) }}">@csrf<button class="btn btn-success btn-sm">Sincronizar</button></form>@endif<button class="btn btn-secondary btn-sm" data-modal-open="access-edit-{{ $access->id }}">Editar</button></div></div>@endforeach</div>@include('partials.pagination',['paginator'=>$accesses])</div>
<x-modal id="access-create" title="Novo usuário de rede" size="lg"><form method="post" action="{{ route('accesses.store') }}">@csrf @include('accesses._form',['access'=>null])</form></x-modal>
@foreach($accesses as $access)<x-modal id="access-edit-{{ $access->id }}" title="Editar usuário de rede" size="lg"><form method="post" action="{{ route('accesses.update',$access) }}">@csrf @method('put') @include('accesses._form',['access'=>$access])</form></x-modal>@endforeach
@endsection
