@extends('layouts.app')
@section('title','Acessos')
@section('content')
<x-page-header title="Credenciais de acesso" description="Usuários Hotspot/PPPoE autorizados pelo FreeRADIUS, isolados por NAS e tenant."><x-slot:actions><button class="btn btn-primary" data-modal-open="access-create">＋ Novo acesso</button></x-slot:actions></x-page-header>
<div class="toolbar"><form class="filter-form"><input class="search-input" name="q" value="{{ request('q') }}" placeholder="Buscar usuário"><button class="btn btn-secondary">Buscar</button></form><span class="cell-subtitle">{{ $accesses->total() }} credencial(is)</span></div>
<div class="card"><div class="table-wrap"><table><thead><tr><th>Usuário</th><th>Cliente</th><th>Serviço</th><th>Plano</th><th>NAS</th><th>Status</th><th></th></tr></thead><tbody>@forelse($accesses as $access)<tr><td><div class="cell-title">{{ $access->username }}</div><div class="cell-subtitle">{{ $access->caller_id ?: 'Sem caller-id' }}</div></td><td>{{ $access->subscriber->name }}</td><td>{{ strtoupper($access->service_type->value) }}</td><td><span class="kbd">{{ $access->plan->rate_limit }}</span><div class="cell-subtitle">{{ $access->plan->name }}</div></td><td>{{ $access->mikrotik?->name ?: 'Qualquer NAS' }}</td><td><x-status-badge :value="$access->status" /></td><td><div class="table-actions"><button class="btn btn-secondary btn-sm" data-modal-open="access-edit-{{ $access->id }}">Editar</button><form method="post" action="{{ route('accesses.destroy',$access) }}">@csrf @method('delete')<button class="btn btn-ghost btn-sm" data-confirm="Excluir esta credencial?">Excluir</button></form></div></td></tr>@empty<tr><td colspan="7"><x-empty-state /></td></tr>@endforelse</tbody></table></div>@include('partials.pagination',['paginator'=>$accesses])</div>
<x-modal id="access-create" title="Nova credencial" size="lg"><form method="post" action="{{ route('accesses.store') }}">@csrf @include('accesses._form',['access'=>null])</form></x-modal>
@foreach($accesses as $access)<x-modal id="access-edit-{{ $access->id }}" title="Editar credencial" size="lg"><form method="post" action="{{ route('accesses.update',$access) }}">@csrf @method('put') @include('accesses._form',['access'=>$access])</form></x-modal>@endforeach
@endsection
