@extends('layouts.app')
@section('title','Histórico MikroTik')
@section('content')
<x-page-header :title="'Histórico · '.$device->name" description="Conexões SSH e comandos controlados, sem exposição de chaves, senhas ou segredos."><x-slot:actions><a class="btn btn-secondary" href="{{ route('mikrotiks.index') }}">Voltar</a></x-slot:actions></x-page-header>

<div class="card" style="margin-bottom:16px"><div class="card-header"><div><div class="card-title">Diagnóstico controlado</div><div class="card-subtitle">Executa somente comandos de leitura presentes na lista de permissão interna.</div></div></div><div class="card-body"><form method="post" action="{{ route('mikrotiks.execute',$device) }}" class="filter-form">@csrf<select name="command_key" required><option value="identity">Identidade e versão</option><option value="health">Recursos e pacotes</option><option value="active-sessions">Sessões ativas</option><option value="hotspot-users">Usuários Hotspot</option><option value="ppp-secrets">Usuários PPPoE</option><option value="hotspot-profiles">Perfis Hotspot</option><option value="ppp-profiles">Perfis PPPoE</option></select><button class="btn btn-primary" data-confirm="Executar comando de diagnóstico no MikroTik?">Executar diagnóstico</button></form></div></div>
<div class="card"><div class="card-header"><div><div class="card-title">Conexões SSH</div><div class="card-subtitle">Testes, autenticações e falhas</div></div></div><div class="table-wrap"><table><thead><tr><th>Data</th><th>Operação</th><th>Destino</th><th>Duração</th><th>Resultado</th><th>Erro</th></tr></thead><tbody>@forelse($connections as $log)<tr><td>{{ optional($log->created_at)->format('d/m/Y H:i:s') }}</td><td>{{ $log->operation }}</td><td>{{ $log->remote_address }}</td><td>{{ $log->duration_ms }} ms</td><td><x-status-badge :value="$log->result" /></td><td>{{ $log->error_message ?: '—' }}</td></tr>@empty<tr><td colspan="6"><x-empty-state /></td></tr>@endforelse</tbody></table></div>@include('partials.pagination',['paginator'=>$connections])</div>
<div class="card" style="margin-top:16px"><div class="card-header"><div><div class="card-title">Comandos executados</div><div class="card-subtitle">Somente comandos da lista permitida</div></div></div><div class="table-wrap"><table><thead><tr><th>Data</th><th>Chave</th><th>Prévia</th><th>Duração</th><th>Resultado</th><th>Saída</th></tr></thead><tbody>@forelse($commands as $log)<tr><td>{{ optional($log->created_at)->format('d/m/Y H:i:s') }}</td><td><span class="kbd">{{ $log->command_key }}</span></td><td>{{ $log->command_preview }}</td><td>{{ $log->duration_ms }} ms</td><td><x-status-badge :value="$log->result" /></td><td><pre class="code">{{ $log->output_excerpt }}</pre></td></tr>@empty<tr><td colspan="6"><x-empty-state /></td></tr>@endforelse</tbody></table></div>@include('partials.pagination',['paginator'=>$commands])</div>
@endsection
