<?php
namespace App\Http\Controllers;
use App\Http\Requests\MikrotikDeviceRequest;
use App\Models\MikrotikDevice;
use App\Services\Audit\AuditLogger;
use App\Services\Mikrotik\MikrotikService;
use App\Services\Security\RadiusCredentialVault;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;
class MikrotikDeviceController extends Controller { public function index(): View { return view('mikrotiks.index',['devices'=>MikrotikDevice::query()->orderBy('name')->paginate(25)]); } public function store(MikrotikDeviceRequest $request,RadiusCredentialVault $vault,AuditLogger $audit): RedirectResponse { $data=$request->safe()->except(['radius_secret']); $data['radius_secret_ciphertext']=$vault->encrypt((string)$request->radius_secret); foreach(['api_ssl','hotspot_enabled','pppoe_enabled','active'] as $field)$data[$field]=$request->boolean($field); $device=MikrotikDevice::query()->create($data); $audit->record('mikrotik.created',$device,[],$device->makeHidden(['api_password','radius_secret_ciphertext'])->toArray()); return back()->with('success','MikroTik cadastrado.'); } public function update(MikrotikDeviceRequest $request,MikrotikDevice $mikrotik,RadiusCredentialVault $vault,AuditLogger $audit): RedirectResponse { $old=$mikrotik->makeHidden(['api_password','radius_secret_ciphertext'])->toArray(); $data=$request->safe()->except(['radius_secret','api_password']); if($request->filled('api_password'))$data['api_password']=$request->api_password; if($request->filled('radius_secret'))$data['radius_secret_ciphertext']=$vault->encrypt((string)$request->radius_secret); foreach(['api_ssl','hotspot_enabled','pppoe_enabled','active'] as $field)$data[$field]=$request->boolean($field); $mikrotik->update($data); $audit->record('mikrotik.updated',$mikrotik,$old,$mikrotik->fresh()->makeHidden(['api_password','radius_secret_ciphertext'])->toArray()); return back()->with('success','MikroTik atualizado.'); } public function destroy(MikrotikDevice $mikrotik,AuditLogger $audit): RedirectResponse { abort_if($mikrotik->accesses()->exists(),422,'MikroTik possui acessos vinculados.'); $audit->record('mikrotik.deleted',$mikrotik,$mikrotik->makeHidden(['api_password','radius_secret_ciphertext'])->toArray(),[]); $mikrotik->delete(); return back()->with('success','MikroTik removido.'); } public function test(MikrotikDevice $mikrotik,MikrotikService $service): RedirectResponse { $result=$service->test($mikrotik); return back()->with($result['ok']?'success':'error',$result['ok']?'Comunicação com RouterOS confirmada.':'Falha: '.$result['error']); } }
